# ---------- STAGE 1: BUILD ----------
FROM node:20-bullseye AS builder

WORKDIR /app

# Ставим всё для sharp и swc
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    libvips-dev \
    curl \
    ca-certificates \
    git \
    && rm -rf /var/lib/apt/lists/*

# ВАЖНО: отключаем prebuilt swc
ENV SWC_BINARY_PATH=none
ENV npm_config_build_from_source=true

COPY strapi/cms/package*.json ./

RUN npm install --include=optional

COPY strapi/cms ./

RUN npm run build