# docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

# Dockerfile.dev
# --------------------------------
# FROM node:20
# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# CMD ["npm", "run", "dev"]