export const Topics = {
    A1: [
        "daily routine",
        "family",
        "food and drinks",
        "shopping",
        "home",
        "weather",
        "school",
        "simple travel",
    ],

    A2: [
        "hobbies",
        "health",
        "friendship",
        "simple work situations",
        "transport",
        "weekend plans",
        "sports",
        "basic technology",
        "daily routine",
        "family",
        "food and drinks",
        "shopping",
        "home",
        "weather",
        "school",
        "simple travel",
    ],

    B1: [
        "city life",
        "nature",
        "memories",
        "unexpected events",
        "communication issues",
        "learning new skills",
        "job interviews",
        "holidays",
        "hobbies",
        "health",
        "friendship",
        "simple work situations",
        "transport",
        "weekend plans",
        "sports",
        "basic technology",
        "daily routine",
        "family",
        "food and drinks",
        "shopping",
        "home",
        "weather",
    ],

    B2: [
        "professional environment",
        "creativity",
        "relationships",
        "difficult decisions",
        "technology",
        "culture and art",
        "travel experiences",
        "society",
        "city life",
        "nature",
        "memories",
        "unexpected events",
        "communication issues",
        "learning new skills",
        "job interviews",
        "holidays",
        "hobbies",
        "health",
        "friendship",
        "simple work situations",
        "transport",
        "weekend plans",
        "sports",
        "basic technology",
        "daily routine",
        "family",
        "food and drinks",
        "shopping",
        "home",
        "weather",
    ],

    C1: [
        "philosophical ideas",
        "psychology",
        "abstract concepts",
        "future predictions",
        "complex moral dilemmas",
        "advanced science",
        "economics",
        "politics",
        "professional environment",
        "creativity",
        "relationships",
        "difficult decisions",
        "technology",
        "culture and art",
        "travel experiences",
        "society",
        "city life",
        "nature",
        "memories",
        "unexpected events",
        "communication issues",
        "learning new skills",
        "job interviews",
        "holidays",
        "hobbies",
        "health",
        "friendship",
        "simple work situations",
        "transport",
        "weekend plans",
        "sports",
        "basic technology",
        "daily routine",
        "family",
        "food and drinks",
        "shopping",
        "home",
        "weather",
    ],
};

export type Level = keyof typeof Topics;

export type Topic =
    | typeof Topics.A1[number]
    | typeof Topics.A2[number]
    | typeof Topics.B1[number]
    | typeof Topics.B2[number]
    | typeof Topics.C1[number];